
name: Bootcamp React Practice app
 
on:
  push:
    branches: [ master ]
 

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Installing NPM
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12  
 
    # Runs a set of commands using the runners shell
    # - name: Github action for yarn
    #   uses: borales/actions-yarn@v2.0.0
    #   with:
    #     cmd: install # will run `yarn install` command
    
    - name: Installing surge
      uses: actions/setup-node@v1
      with:
        node-version: 8
      run: npm install --global surge
    - name: Deploying Using Surge
      run: surge ./ http://bootcamp-react-practice.surge.sh --token ${{ secrets.SURGE_TOKEN }}
